EXPLAIN ANALYZE SELECT * FROM tasks WHERE userId = 1;
EXPLAIN ANALYZE SELECT * FROM contacts WHERE userId = 1;
EXPLAIN ANALYZE SELECT * FROM notes WHERE contactId = 1;
EXPLAIN ANALYZE SELECT * FROM refresh_tokens WHERE userId = 1;
